// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsGp_Ne8ZQelAEmuhD7YWOwdAXG7oNQs',
    appId: '1:93532617575:web:638d8a18a162fde4128dc2',
    messagingSenderId: '93532617575',
    projectId: 'look-fashion-app',
    authDomain: 'look-fashion-app.firebaseapp.com',
    storageBucket: 'look-fashion-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5NBxzfL3eZux-p_agGMrUDCji7mUkbAA',
    appId: '1:93532617575:android:91f494f78d1d6e9a128dc2',
    messagingSenderId: '93532617575',
    projectId: 'look-fashion-app',
    storageBucket: 'look-fashion-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSh98TJwO3cNUkVGjhswCS1a7eEw3wpck',
    appId: '1:93532617575:ios:bf347cb693ad082f128dc2',
    messagingSenderId: '93532617575',
    projectId: 'look-fashion-app',
    storageBucket: 'look-fashion-app.firebasestorage.app',
    iosBundleId: 'com.example.myFashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSh98TJwO3cNUkVGjhswCS1a7eEw3wpck',
    appId: '1:93532617575:ios:bf347cb693ad082f128dc2',
    messagingSenderId: '93532617575',
    projectId: 'look-fashion-app',
    storageBucket: 'look-fashion-app.firebasestorage.app',
    iosBundleId: 'com.example.myFashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKsGp_Ne8ZQelAEmuhD7YWOwdAXG7oNQs',
    appId: '1:93532617575:web:0127e0a63a909184128dc2',
    messagingSenderId: '93532617575',
    projectId: 'look-fashion-app',
    authDomain: 'look-fashion-app.firebaseapp.com',
    storageBucket: 'look-fashion-app.firebasestorage.app',
  );
}
